name: Build Apktool JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    name: Build apktool.jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated v3 -> v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Updated v3 -> v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4 # Updated v3 -> v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Build Apktool JAR
        run: |
          chmod +x gradlew
          ./gradlew clean shadowJar

      - name: Upload apktool.jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: apktool-jar
          # Updated path to point to the cli build directory
          path: brut.apktool/apktool-cli/build/libs/*.jar
